#!/usr/bin/env bash

PKG_DIR="$(dirname "$(realpath "$0")")"

export CARGO_HOME="${PKG_DIR}/CARGO_HOME"

export RUSTUP_HOME="${PKG_DIR}/RUSTUP_HOME"

init(){
  $PKG_DIR/rustup-init --profile minimal -q -y
}

echo $PKG_DIR
echo $CARGO_HOME
echo $RUSTUP_HOME


COMMAND="$(basename "$0")"

if ! [[ -d $CARGO_HOME ]]; then
  init
fi

exec $CARGO_HOME/bin/$COMMAND "$@"
